### ISSUE TITLE
how we can use MPIIGaze dataset

### ISSUE THREAD

**Issue by nastaran-amini** [Walleclipse/Gaze_Tracking#3]
when i want to use MPIIGaze dataset for this code i have many error for load data..  finally i found that this dataset is not match to this gitub code . annotation and test and train data completely different  from your code especially headloader fun. please guide me  which dataset is match to your code . thanks

**Comment by Walleclipse** [comment]
Hi，

Sorry for the inconvenience. My data set is collected by a company. Which is private. 
For the public dataset, Please check the data description part of  [Zhu_Monocular_Free-Head_3D_ICCV_2017](http://openaccess.thecvf.com/content_ICCV_2017/papers/Zhu_Monocular_Free-Head_3D_ICCV_2017_paper.pdf).

You need to prepare your dataset to follow my data format, please check [sample_data](https://github.com/Walleclipse/Gaze_Tracking/tree/master/sample_data).
1) Save images of the pose of the head, left eye, and right eye in the folder of `head`, `l_eye`, and `r_eye`.
2) Save ground-truth (3-d) value of the head pose and eye pose in `head_label.txt` and `eye_label.txt`. Then save the final gaze label in `gaze_label.txt`.

According to the [Zhu_Monocular_Free-Head_3D_ICCV_2017](http://openaccess.thecvf.com/content_ICCV_2017/papers/Zhu_Monocular_Free-Head_3D_ICCV_2017_paper.pdf), there is a geometric constrains between the pose of the head, eye, and gaze vectors.
